name: free_brew
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  liquid_progress_indicator: ^0.3.2
  cupertino_icons: ^1.0.2
  audioplayers: ^0.19.0
  android_alarm_manager_plus: ^1.1.0
  flutter_launcher_icons: ^0.9.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - "assets/hand-bell-ringing-sound.wav"
    - "assets/icon_simple.png"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon_simple.png"
  adaptive_icon_foreground: "assets/icon_simple_padding.png"
  adaptive_icon_background: "#2196f3"